config/routes.rb
DiabetesHealth::Application.routes.draw do

  root :to =>'static_pages#home'

  match '/diabetes' => 'static_pages#diabetes', :via => 'get'
  match '/publications' => 'static_pages#publications', :via => 'get'
  match '/relatedarticles' => 'static_pages#related_articles', :via => 'get'
  match '/exercise' => 'static_pages#exercise', :via => 'get'
  match '/recipes' => 'static_pages#recipes', :via => 'get'
  match '/nutritionnews' => 'static_pages#nutrition_news', :via => 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def diabetes

  end

  def publications

  end


  def exercise
  end

  def related_articles
  end

  def recipes

  end

  def nutrition_news
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.erb
<div class="row" id="topper">
   <div class="col-md-12">

   </div>
</div>
<div class="carousel-inner row-fluid" id="myCarousel" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>

    </ol>
    <div class = "carousel-inner">
    <div class="active item"><img src="/assets/rsz_fruit.jpg"  class="list_image img-polaroid">
    <div class = "carousel-caption">
      <h3>Nutrition</h3>
      <p>Learn about recent health articles regarding diabetes</p>
    </div>
    </div>
    <div class="item"><img src="/assets/rsz_books.jpg">
      <div class="carousel-caption">
        <h3>Publications</h3>
        <p>View terrific sources of information for maintaining and balancing
        your health</p>
      </div>
      </div>
    <div class="item"><img src="/assets/rsz_cooking.jpg">
      <div class="carousel-caption">
        <h3>Cooking</h3>
        <p>Scour through the website for tips and hints on maximizing the health value
        of the food we cook.  Also, a terrific source for recipes for fantastic meals</p>
      </div>
    </div>
    <div class="item"><img src="/assets/rsz_cycle.jpg">
      <div class="carousel-caption">
      <h3>Exercising</h3>
      <p>As we all know, exercise plays a  pivotal role in maintaining a healthy lifestyle.
      Look at tips and tricks for maximizing the time we do have for fitness</p>
      </div>
    </div>
    <div class="item"><img src="/assets/rsz_newspaper.jpg">
      <div class="carousel-caption">
        <h3>Article Posts</h3>
        <p>Look through various posts about related articles regarding
        health, nutrition, and much, much more.</p>
      </div>

    </div>

    </div>
   <!-- <a class="carousel-control left" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-right"></span></a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">
      <span class=" icon-chevron-right"></span></a>   -->
    <a href="#myCarousel" class="left carousel-control" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"></span></a>
    <a href="#myCarousel" class="right carousel-control" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>

  </div>
<nav class="navbar navbar-inverse  ">
  <div class=" navbar-inner navbar-nav">
    <ul class="nav pull-left">
      <li><%= link_to "D Health & Lifestyle.com",    root_path, class: "navbar-brand active" %></li>
    </ul>
    <ul class="nav pull-left">
      <li><%= link_to "Diabetes",    diabetes_path %></li>
    </ul>
    <ul class="nav pull-left ">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle"data-toggle="dropdown" >Health <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Exercise", exercise_path%></li>
          <li><%= link_to "Related Articles", relatedarticles_path%> </li>
        </ul>
      </li>
    </ul>
    <ul class="nav pull-left">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Nutrition <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Nutrition News", nutritionnews_path %></li>
          <li><%=link_to "Recipes", recipes_path %></li>
        </ul>
      </li>
    </ul>
    <ul class="nav pull-left">
      <li><%= link_to "Publications", publications_path %></li>
    </ul>

    <form class="navbar-form navbar-right" >
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
  </div>
</nav>


  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script src="vendor/assets/javascripts/bootstrap.min.js"></script>

  <script>
      $(function(){
          $('#myCarousel').carousel(  {
               interval: 4000
          });
      });
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diabetes Health & Lifestyle | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all",
                                "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
 <div class="container">
<%= yield %>
 </div>
<footer>
  <div class="navbar navbar-inverse" id="footer">
  <div class="navbar-inner navbar-nav">
    <ul class="nav pull-left">
    <li><%= link_to "Home", root_path %></li>
    </ul>
    <ul class="nav pull-left">
    <li><%= link_to "Diabetes", diabetes_path %></li>
    </ul>
    <ul class="nav pull-left">
      <li><%= link_to "Exercise", exercise_path %></li>
    </ul>
    <ul class="nav pull-left">
      <li><%= link_to "Recipes", recipes_path %></li>
    </ul>
  </div>
  </div>
</footer>
</body>
</html>

app/views/static_pages/diabetes.html.erb
<%= provide(:title, 'Diabetes') %>

<body>
    <div class="row-fluid col-lg-8 col-lg-offset-2 " >
        <div class="page-header text-center">
         <h1> Diabetes and You</h1>
          </div>
         <h3>What is Diabetes?</h3>
         <p> Quite simply, Diabetes occurs when a person has a high blood sugar due to a person's
         pancreas not creating enough insulin, or from a person's cells not responding properly to insulin produced
         in the body.</p>
          <h3> Symptoms</h3>
          <p> There are several other symptoms to look out for, but these are the ones that are primarily
          the ones to look out for.  </p>
          <ul>
            <li> Constant urination</li>
            <li>Blurry vision</li>
            <li> Numbness in the hands and/or feet</li>
            <li> Inability to heal quickly</li>
            <li>n Extreme thirst</li>
            <li> Extreme fatigue</li>
          </ul>
          <h3>Forms of Diabetes</h3>
          <ul class="nav nav-tabs">
            <li class="active"><a href="#t1" data-toggle="tab" >Type 1</a></li>
            <li><a href="#t2" data-toggle="tab">Type 2</a></li>
          </ul>
          <section class="tab-content text-center">
            <article class="tab-pane active fade in" id="t1">
             <h3>Type 1 Diabetes</h3>
              <br>

              <p>Type 1 diabetes is generally diagnosed in children and young adults.
              It occurs when a person's pancreas can no longer produce any insulin. Only 5 percent of
              people who are diagnosed with the disease diabetes have type 1.  Type 1 was generally referred
              to as juvenile diabetes.</p>
            </article>
            <article class="tab-pane fade in"  id="t2">
              <h3>Type 2 Diabetes</h3>
              <br>
              <p> If you are diagnosed with type 2 diabetes, your body is not correctly using
              the insulin produced by your body.  This is referred to as insulin resistance.
              Over time, however, your body can not keep up with the insulin needed to maintain
              a healthy lifestyle.</p>
              <p>Type 2 diabetes is the most common form of diabetes</p>
            </article>
          </section>
           <article >
            <h3> What is Hemoglobin A1c?</h3>
            <p>When a doctor wants to test your Hemoglobin A1C, what he really wants to look at is your
            red blood cells.  Sugar sticks to proteins in our body.  Red blood cells have an average
            life span of three months and so the test allows the doctor to see how much sugar  has
            stuck to the red blood cells over a period of time.  It is a better way of looking at
            a person's control of their diabetes over a range of time.</p>
           </article>
            <hr>
            <h3>A1c Ranges</h3>
           <table class="table text-center table-striped table-bordered table-hover" >
             <tr>
               <th class="text-center">A1c(%)</th>
               <th class="text-center">Expected average of blood sugar</th>
             </tr>
             <tr class = "warning ">
               <td>5</td>
               <td>97</td>
             </tr>
             <tr class="success active">
               <td>6</td>
               <td> 135</td>
             </tr>
             <tr class="warning">
               <td>7</td>
               <td>170</td>
             </tr>
             <tr class="success ">
               <td> 8</td>
               <td>205</td>
             </tr>
             <tr class="warning">
               <td>9</td>
               <td>240</td>
             </tr>
             <tr class="success">
               <td>10</td>
               <td>275</td>
             </tr>
             <tr class="warning">
               <td>11</td>
               <td>310</td>
             </tr>
             <tr class="success">
               <td>12</td>
               <td>345</td>
             </tr>
           </table>
    </div>     <!--   #this marks the end of the content -->
</body>

app/views/static_pages/exercise.html.erb
<% provide(:title, 'Exercise') %>
<body>
  <div class="row">
    <div class="row col-lg-8 col-lg-offset-2">
      <div class="thumbnail">
        <h1>how and why is this happening to me?</h1>
      </div>
      <div class="thumbnail">
        <h1>who are you?</h1>
      </div>
    </div>
  </div>
</body>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<body xmlns="http://www.w3.org/1999/html">
        <div class="row-fluid ">
          <div class="col-lg-8 col-lg-offset-2   text-center">
            <h1> Welcome to Diabetic Health & Lifestyle</h1>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
            <h2>Purpose</h2>
          </div>
        </div>
        <div class="row">
          <article class="col-lg-8 col-lg-offset-2 text-center">
              <p> The main purpose of this website to provide people with diabetes a variety of resources that they
                  can utilize to ensure a higher quality of life.  There are already several great websites, blogs, and
                  so forth dedicated to helping those inflicted with the disease of diabetes, but most are piecemeal.  The goal
                  of the website, is to provide the viewer with up-to-date articles regarding the whole spectrum of diabetes,
                  ranging from maximizing fitness for better management of diabetes to recipes that incorporate new food
                  substitution techniques to lower caloric intake.</p>
              <hr/>
              <br>
          </article>
        </div>
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
            <h1>About</h1>
            <p> The developer of the website was diagnosed with Type 1 Diabetes at the age of 14.
            From all of the years of researching and through the process of trial and errror,
            has become a terrific source of knowledge with several facets of diabetes.  He feels
            that there should be a simple, easy website that highlights various factors of diabetes and how
            one can improve their lives. </p>
          </div>
        </div>
</body>

app/views/static_pages/nutrition_news.html.erb
<%provide(:title, 'Home') %>

app/views/static_pages/publications.html.erb
<%= provide(:title, 'Publications') %>
<body>
  <div class="row col-lg-8 col-lg-offset-2">
    <div class = "page-header text-center">
        <h1> A Short List of Terrific Works</h1>
    </div>
  </div>   <!--this is the end of the container-->

   <div class="row col-lg-8 col-lg-offset-2">
    <div class="thumbnail">
      <div class="row">
      <div class = " col-lg-4 col-lg-offset-2 ">
        <h4>American Diabetes Association</h4>
        <p>A terrific website for all things diabetes.</p>
      </div>
      <div class="col-lg-4">
        <a href="http://www.diabetes.org">
        <img src="/assets/americandiabetes.tiff"> </a>
      </div>
      </div>
    </div>
   </div>


   <div class=" row col-lg-9 col-lg-offset-3">
     <div class="page-header">
       <h1>where is this all going? aaaaaaaaaaaaaaaaaaaaaaaaaa</h1>
     </div>
     <div class="thumbnail">
         <div class = " col-lg-4  ">
           <h4>Why won't you fucking work?</h4>
         </div>
         <div class="col-lg-4">
           <p>What are you?</p>
       </div>
     </div>
   </div>
</body>

app/views/static_pages/recipes.html.erb
<% provide(:title, 'Recipes') %>

app/views/static_pages/related_articles.html.erb
<% provide(:title, 'Related Articles') %>